LiamHjalmarsson/MOCHA_Movies

php/post/following.php
php/post/watched-movies.php

Post following & post watched movies

---

php/patch/change-notification.php
php/post/new-review.php

Change notification

---

php/patch/change-user.php
php/patch/patch.php

Create change user.php

---

php/delete/delete-movies-to-see.php
php/delete/delete-review.php
php/delete/delete-subscribed-movies.php
php/delete/delete-watched-movies.php
php/functions/functions.php

update to delete functions

---

php/dataset.json
php/delete/delete-following.php
php/delete/delete-movies-to-see.php
php/delete/delete-review.php
php/delete/delete-subscribed-movies.php
php/delete/delete-watched-movies.php
php/functions/functions.php
php/get/get.php

Get and Delete should be fine for now

tests completed and fixes adjusted

---

php/dataset.json
php/delete/delete-following.php
php/delete/delete-movies-to-see.php
php/delete/delete-subscribed-movies.php
php/delete/delete-watched-movies.php

Fixed some and started created users

---

php/dataset.json
php/post/new-review.php

added info to users to use in dataset and fixed so you don't get a notification on you own review

added info to use in dataset

---

js/showmovies/showmovies.css
js/showmovies/showmovies.js
js/showmovies/test.php

Two options, commented code optional to work but creates new container each time filtering.. Now it fills on the same container.
POPULAR function is to be removed only to see so it works

rendermovies, createMovie

---

js/StartUp/logIn.css
js/StartUp/start-up.js
php/post/new-user.php

LogIn removes the logInDiv and saves user in localstorage SignUp posts new user and adds log in page
#36 done
#37 done

logIn and signUp working in tandem

---

js/moviepage/moviepage.js

some inforatiom about movie

---

js/user/index.php
js/user/style_stars.css
js/user/user.js

Stars that get more full and a number grade that is available

Grade system functioning

---

js/StartUp/start-up.js
js/user/user.js
php/dataset.json

#173 done
The function for logging in will only be called if you are not logged in

Stay logged in unless logged out

---

js/moviepage/movieIcons.js
js/moviepage/moviepage.css
php/index.php

#183 Done
Stars will now act with the mouse and fill in the stars

Stars in review fix

---

js/allMovies/allMovies.css
js/homepage/homepage.css
js/search/search.css
js/showmovies/showmovies.css

gone over img size and margin

---

js/user/user-profile.css
js/user/user.js

Styled icons and buttons in users and started the change profile function.

Users buttons icons

---

js/showmovies/showmovies.css
js/showmovies/showmovies.js

control if there is any movies of not

small update

---

js/user/user.js
php/dataset.json
php/image/update-image.php

You can now pick a file and upload it to the site. image link will append to user in dataset

Upload images working

---

php/image/update-image.php

Images will now be put in the upload file and have correct directory in dataset

change uploadfile and directory

---

js/user/user-profile.css
js/user/user.js

#179 done
You can now edit your username and password through your user profile

Password and Username changable

---

js/StartUp/logIn.css
js/StartUp/start-up.js

first edit on log in styling, will add more tomorrow :)

first edit on log in styling

---

js/user/user.js
php/dataset.json

When changing username, password or image localstorage now updates

localstorage bug fixes

---

js/fellows/fellows.css
js/homepage/homepage.js
js/search/search.js
js/showmovies/showmovies.css

buttons refresh
